<?xml version="1.0"?>
<robot name="IEEE_sample_bot" xmlns:xacro="http://ros.org/wiki/xacro"
            xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
            xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
            xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

  <!-- <xacro:include filename="/home/raghav/IEEE_sample_bot/src/sauntr_description/urdf/sauntr_plugins.xacro"/> -->

  <!-- DEFINING GENERIC PROPERTIES THAT ARE USED IN THE XACRO FILE -->

  <!-- along x axis -->
  <xacro:property name="base_length" value="0.5"/>
  <!-- along y axis -->
  <xacro:property name="base_width" value="0.5"/>
  <!-- along z axis -->
  <xacro:property name="base_height" value="0.1"/>
  <xacro:property name="base_mass" value="5"/>
  <xacro:property name="wheel_dia" value="0.1"/>
  <xacro:property name="wheel_height" value="0.05"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  <xacro:property name="camera_size" value="0.1"/>
  <xacro:property name="camera_link_name" value="camera"/>
  <xacro:property name="camera_mass" value="0.4"/>
  <xacro:property name="laser_link_name" value="hokuyo"/>
  <xacro:property name="laser_height" value="0.02"/>
  <xacro:property name="laser_width" value="0.02"/>
  <xacro:property name="laser_length" value="0.3"/>
  <xacro:property name="laser_mass" value="0.2"/>

  <!-- COLOURS FOR MATERIAL -->
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="black">
    <color rgba ="0 0 0 1"/>
  </material>

  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>

  <!-- MACROS FOR INERTIAL PROPERTIES -->
  <xacro:macro name="base_inertial">
    <inertial>
      <mass value="${base_mass}" />
      <inertia ixx="${(1/12)*base_mass*((base_width*base_width)+(base_height*base_height))}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(1/12)*base_mass*((base_height*base_height)+(base_length*base_length))}"
        iyz="0.0"
        izz="${(1/12)*base_mass*((base_width*base_width)+(base_length*base_length))}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="wheel_inertial">
    <inertial>
      <mass value="${wheel_mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="camera_inertial" params="camera_mass">
    <inertial>
      <mass value="${camera_mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="hokuyo_inertial" params="laser_mass">
    <inertial>
      <mass value="${laser_mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>


  <!-- MACRO FOR GENERIC WHEEL. SUPPLY PARAMS TO PLACE THEM, JOINT INCLUDEDE IN MACRO -->
  <xacro:macro name="wheel" params="left_right front_back relx rely">
    <link name="${left_right}_${front_back}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_dia/2}" length="${wheel_height}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_dia/2}" length="${wheel_height}"/>
        </geometry>
      </collision>
      <xacro:wheel_inertial/>
    </link>

    <joint name="${left_right}_${front_back}_wheel_to_base_link" type="continuous">
      <origin xyz="${relx*((base_length/2)-wheel_dia/2)} ${rely*((base_width/2-wheel_height/2))} ${wheel_dia/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${left_right}_${front_back}_wheel"/>
    </joint>
  </xacro:macro>

  <!-- MACRO FOR PHYSICAL ASPECTS OF CAMERA -->
  <xacro:macro name="camera" params="parent_link name camera_size camera_mass joint_x joint_y joint_z">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 -0.1 0"/>
        <geometry>
          <box size="${camera_size} ${camera_size} ${camera_size}"/>
        </geometry>
        <material name="green"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 -0.1 0"/>
        <geometry>
          <box size="${camera_size} ${camera_size} ${camera_size}"/>
        </geometry>
      </collision>
      <xacro:camera_inertial camera_mass="${camera_mass}"/>
    </link>

    <joint name="${name}_to_${parent_link}" type="fixed">
      <origin xyz="${joint_x} ${joint_y} ${joint_z}" rpy="0 0 0"/>
      <axis xyz="0 0 1" rpy="0 0 0"/>
      <parent link="${parent_link}"/>
      <child link="${name}"/>
    </joint>
  </xacro:macro>

  <!-- MACRO FOR PHYSICS ALSPECT OF LASER SCANNER -->
  <xacro:macro name="hokuyo_laser_scanner" params="parent_link name laser_height laser_width laser_length laser_mass joint_x joint_y joint_z">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${laser_width} ${laser_length} ${laser_height}"/>
        </geometry>
        <material name="green"/>
      </visual>
      <collision>
        <geometry>
          <box size="${laser_width} ${laser_length} ${laser_height}"/>
        </geometry>
      </collision>
      <xacro:hokuyo_inertial laser_mass="${laser_mass}"/>
    </link>

    <joint name="${name}_to_${parent_link}" type="fixed">
      <origin xyz="${joint_x} ${joint_y} ${joint_z}" rpy="0 0 0"/>
      <axis xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${parent_link}"/>
      <child link="${name}"/>
    </joint>
  </xacro:macro>

  <!-- BASE LINK. MAIN BOX TO WHICH WHEEL AND EVERYTHING ELSE IS TO BE ATTACHED -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${wheel_dia + base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${wheel_dia + base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:base_inertial/>
  </link>

  <!-- CREATING AN INSTANCE OF EACH WHEEL -->
  <xacro:wheel left_right="left" front_back="front" relx="1" rely="1"/>
  <xacro:wheel left_right="left" front_back="back" relx="-1" rely="1"/>
  <xacro:wheel left_right="right" front_back="back" relx="-1" rely="-1"/>
  <xacro:wheel left_right="right" front_back="front" relx="1" rely="-1"/>

  <!-- SETTING UP THE PLUGIN FOR FOUR WHEEL DIFFERENTIAL -->
  <gazebo>
    <plugin name="four_wheel_differential_plugin" filename="/home/raghav/IEEE_sample_bot/devel/lib/libfour_wheel_differential_plugin.so">
      <front_left_joint>left_front_wheel_to_base_link</front_left_joint>
      <back_left_joint>left_back_wheel_to_base_link</back_left_joint>
      <front_right_joint>right_front_wheel_to_base_link</front_right_joint>
      <back_right_joint>right_back_wheel_to_base_link</back_right_joint>
    </plugin>
  </gazebo>

  <!-- CREATNG AN INSTANNCE OF A CAMERA -->
  <xacro:camera parent_link="base_link" name="${camera_link_name}" camera_size="${camera_size}" camera_mass="${camera_mass}" joint_x="${base_length/4}" joint_y="0" joint_z="${wheel_dia+base_height+camera_size/2}"/>

  <!-- CREATING AN INSTANCE OF LASER SCANNER -->
  <xacro:hokuyo_laser_scanner parent_link="base_link" name="${laser_link_name}" laser_height="${laser_height}" laser_width="${laser_width}" laser_length="${laser_length}" laser_mass="${laser_mass}" joint_x="${base_length/2+laser_width/2}" joint_y="0" joint_z="${wheel_dia+base_height/2}"/>
</robot>
